### ISSUE TITLE
Additional arguments with strange side effects

### ISSUE THREAD

**Issue by kraih** [sfodje/perltidy#1]
Not sure what's going on, but when i set `"perltidy.additionalArguments": ["-pro=.../.perltidyrc"]` this extension creates perl processes that run forever and keep a CPU core busy (processes had to be killed manually). Tested with macOS 10.12.5, VS Code 1.14.1 Perl 5.26.0 and Perl::Tidy 20170521. For the Atom perltidy package i've used that as the default for a long time without problem. https://github.com/kraih/atom-perltidy/blob/master/index.js#L14

**Comment by kraih** [comment]
Same result for `"perltidy.profile": ".../.perltidyrc"`.

**Comment by kraih** [comment]
This problem has been fixed in [perltidy-more](https://marketplace.visualstudio.com/items?itemName=Kaktus.perltidy-more).

**Comment by sfodje** [comment]
Hello Sebastien,
I've been busy with another project, I'll make time to implement a fix for this issue with the next week. 
Thanks so much for raising the problem.

**Comment by sfodje** [comment]
Thanks again for bringing up this issue. Looks like the fix in [perltidy-more](https://marketplace.visualstudio.com/items?itemName=Kaktus.perltidy-more) is simply to set the file directory as the working directory of the process so I implemented the same fix.

I hate to see duplicated work. It may be worth combining perltidy and perltidy-more into one extension. I'll reach out to the author.
